### ISSUE TITLE
[TEST] Community Call 2021-12-14

### ISSUE THREAD

**Issue by t-lo** [flatcar-linux/Flatcar#569]
## TODOS and owners
   - [ ] 1 week before meeting: Create Agenda PR @[owner]
   - [ ] 1 week before meeting: Tweet "ask for input" @[owner] w/ link to agenda PR (so people can add topcis)
   - [ ] Monday before meeting: Finish and merge Agenda @[owner]
   - [ ] Monday before meeting: Tweet announcement @[owner]
   - [ ] 1h before meeting: announce in matrix (w/ Zoom link) @[owner]
   - [ ] Start meeting, add recording link to agenda @[owner]
   - [ ] conduct meeting @[owner]
   - [ ] after meeting, add slides (PDF) to agenda @[owner]
